#!/usr/bin/env python3
"""
Module 8: Knowledge Graph Builder (Interactive Policy Visualization)
Consumes Module 5 (candidate_pairs.json) and Module 3 (extracted_json/).
Prepares to absorb Module 6 (LLM Reasoning) and Module 7 (Staleness).
"""
import json
import logging
import hashlib
import colorsys
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Optional, Set, Any, Tuple

import networkx as nx
from pyvis.network import Network

# ------------------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------------------
JSON_DIR = Path("extracted_json")
CANDIDATE_FILE = Path("output/candidate_pairs.json")
OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True)

# Setup logger
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("graph_service")

# ------------------------------------------------------------------
# DYNAMIC COLOR GENERATION (Golden Ratio - Scalable to 1000+ policies)
# ------------------------------------------------------------------
SPECIAL_POLICY_COLORS = {
    "POL-002": "#E74C3C",  # Red (highlight Cloud Policy)
    "POL-049": "#2ECC71",  # Green (highlight Password Policy)
}

def get_policy_color(policy_id: str) -> str:
    """Returns a visually distinct hex color for any policy ID using Golden Ratio."""
    if policy_id in SPECIAL_POLICY_COLORS:
        return SPECIAL_POLICY_COLORS[policy_id]
    
    hash_int = int(hashlib.md5(policy_id.encode()).hexdigest(), 16)
    hue = (hash_int * 0.618033988749895) % 1.0
    r, g, b = colorsys.hsv_to_rgb(hue, 0.65, 0.85)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

# ------------------------------------------------------------------
# DATA LOADERS (with caching for performance)
# ------------------------------------------------------------------
@lru_cache(maxsize=1)
def load_obligations_metadata() -> Dict[str, Dict[str, Any]]:
    """Load all obligations from extracted_json/ and return a metadata dict."""
    obligations = {}
    json_files = list(JSON_DIR.glob("*.json"))
    
    if not json_files:
        logger.warning(f"No JSON files found in '{JSON_DIR}'.")
        return obligations

    for json_path in json_files:
        policy_name = json_path.stem
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        if isinstance(data, dict) and "obligations" in data:
            items = data["obligations"]
        elif isinstance(data, list):
            items = data
        else:
            logger.warning(f"Skipping {json_path.name}: Unexpected JSON structure.")
            continue

        for item in items:
            if "obligation_id" in item:
                ob_id = item["obligation_id"]
            elif "id" in item:
                ob_id = f"{policy_name}-{item['id']}"
            else:
                idx = items.index(item) + 1
                ob_id = f"{policy_name}-OBL-{idx:03d}"
            
            text = item.get("text") or item.get("original_text") or "No text available"
            topic = item.get("topic", "unknown")
            
            obligations[ob_id] = {
                "text": text,
                "topic": topic,
                "policy": policy_name,
                "strength": item.get("strength", "Unknown"),
                "actor": item.get("actor", ""),
                "action": item.get("action", ""),
                "object": item.get("object", ""),
                "scope": item.get("scope", ""),
                "is_stale": False,  # Placeholder for Module 7
            }
    
    logger.info(f"Loaded metadata for {len(obligations)} obligations.")
    return obligations

def load_candidate_pairs() -> Optional[Dict[str, Any]]:
    """Load the candidate_pairs.json generated by Module 5."""
    if not CANDIDATE_FILE.exists():
        logger.error(f"Candidate file not found: {CANDIDATE_FILE}")
        return None
    
    with open(CANDIDATE_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    logger.info(f"Loaded {data['metadata']['total_pairs']} candidate pairs.")
    return data

def load_module6_results() -> Dict[Tuple[str, str], Dict[str, Any]]:
    """PLACEHOLDER: Replace with actual Module 6 data when ready."""
    return {}

def load_stale_obligations() -> Set[str]:
    """PLACEHOLDER: Replace with actual Module 7 data when ready."""
    return set()

# ------------------------------------------------------------------
# GRAPH BUILDER
# ------------------------------------------------------------------
def build_graph(
    module6_results: Optional[Dict[Tuple[str, str], Dict[str, Any]]] = None,
    stale_ids: Optional[Set[str]] = None,
) -> nx.Graph:
    """Build the Knowledge Graph from Module 3, 5, 6, and 7 data."""
    if module6_results is None:
        module6_results = load_module6_results()
    if stale_ids is None:
        stale_ids = load_stale_obligations()

    obligations = load_obligations_metadata()
    candidate_data = load_candidate_pairs()
    
    if not obligations or not candidate_data:
        logger.error("Missing required data to build graph.")
        return nx.Graph()

    G = nx.Graph()

    # --- 1. Add Nodes (Obligations) ---
    for ob_id, meta in obligations.items():
        is_stale = ob_id in stale_ids
        policy = meta["policy"]
        color = get_policy_color(policy)
        
        G.add_node(
            ob_id,
            label=ob_id[:6]+ob_id[-8:],  # CLEAN LABEL: Just the ID
            title=meta["text"],  # Full text on hover
            group=meta["topic"],
            policy=policy,
            topic=meta["topic"],
            strength=meta["strength"],
            is_stale=is_stale,
            color=color,
            shape="diamond" if is_stale else "dot",  # Visual flag for staleness
        )

    # --- 2. Add Edges (NO VISIBLE LABELS - details only in tooltip) ---
    module6_lookup = {
        (a, b): val for (a, b), val in module6_results.items()
    }

    for pair in candidate_data.get("flat_pairs", []):
        a_id = pair["obligation_a_id"]
        b_id = pair["obligation_b_id"]
        
        if a_id not in G or b_id not in G:
            continue

        # Determine edge color and build a rich tooltip (title)
        pair_key = tuple(sorted([a_id, b_id]))
        
        if pair_key in module6_lookup:
            rel = module6_lookup[pair_key]
            relation_type = rel["relation_type"]
            edge_color = {
                "CONFLICT": "#F44336",
                "SUPERSEDED": "#FF9800",
                "COMPLEMENTARY": "#4CAF50",
            }.get(relation_type, "#2196F3")
            
            # Build detailed tooltip for Module 6 edges
            title = (
                f"Type: {relation_type}\n"
                f"Severity: {rel.get('severity', 'MEDIUM')}\n"
                f"Reason: {rel.get('llm_reason', 'No reason provided.')}"
            )
        else:
            # Fallback to Module 5 auto-classification
            auto_class = pair.get("auto_classification")
            if auto_class == "REDUNDANT_AUTO":
                edge_color = "#9E9E9E"
                title = "Auto-resolved duplicate (identical wording)"
            else:
                # Unclassified -> show as 'Similar' with score in tooltip only
                edge_color = "#2196F3"
                title = (
                    f"Semantic Match (Score: {pair['similarity']:.3f})\n"
                    f"Topic A: {pair['topic_a']}\n"
                    f"Topic B: {pair['topic_b']}"
                )
        
        # Add the edge with NO VISIBLE LABEL (empty string)
        G.add_edge(
            a_id,
            b_id,
            color=edge_color,
            label="",  # <-- EMPTY STRING = NO TEXT ON EDGE
            title=title,  # <-- TOOLTIP ONLY (visible on hover)
            severity="HIGH" if edge_color == "#F44336" else "MEDIUM",
            weight=pair.get("similarity", 0.5),
        )

    logger.info(f"Graph built: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges.")
    return G

def filter_graph_by_policies(G: nx.Graph, selected_policies: List[str]) -> nx.Graph:
    """Return a subgraph containing only obligations from the selected policies."""
    if not selected_policies:
        return G
    
    nodes_to_keep = [
        node for node, attrs in G.nodes(data=True)
        if attrs.get("policy") in selected_policies
    ]
    return G.subgraph(nodes_to_keep)

# ------------------------------------------------------------------
# PYT VIS GENERATOR (WITH SPREAD OUT PHYSICS)
# ------------------------------------------------------------------
def generate_pyvis_html(G: nx.Graph, height: str = "850px") -> str:
    """Convert NetworkX graph to an interactive PyVis HTML string."""
    if G.number_of_nodes() == 0:
        return "<div style='padding:20px;'>No graph data available. Upload policies and run /match first.</div>"
    
    net = Network(height=height, width="100%", directed=False, notebook=True, bgcolor="#ffffff", font_color="black")
    
    # Add nodes
    for node, attrs in G.nodes(data=True):
        net.add_node(
            node,
            label=attrs.get("label", node),  # Clean ID
            title=attrs.get("title", ""),   # Full text on hover
            color=attrs.get("color", "#2196F3"),
            group=attrs.get("topic", "unknown"),
            shape=attrs.get("shape", "dot"),
            borderWidth=3 if attrs.get("is_stale") else 2,
            shadow=True,
        )
    
    # Add edges (with no visible label)
    for u, v, attrs in G.edges(data=True):
        net.add_edge(
            u,
            v,
            color=attrs.get("color", "#2196F3"),
            label="",  # <-- FORCES NO TEXT ON THE EDGE
            title=attrs.get("title", ""),  # Tooltip only
            width=3 if attrs.get("severity") == "HIGH" else 1.5,
            smooth=True,
        )
    
    # PHYSICS CONFIGURATION: MAXIMUM SPREADING
    net.set_options("""
    var options = {
      "physics": {
        "forceAtlas2Based": {
          "gravitationalConstant": -50,
          "centralGravity": 0.01,
          "springLength": 500,
          "springConstant": 0.08,
          "damping": 0.4
        },
        "maxVelocity": 50,
        "solver": "forceAtlas2Based",
        "stabilization": {
          "enabled": true,
          "iterations": 1500,
          "updateInterval": 50
        }
      },
      "edges": {
        "font": { "size": 10, "background": "white", "strokeWidth": 0 },
        "smooth": { "enabled": true, "type": "continuous" }
      },
      "nodes": {
        "font": { "size": 14, "face": "arial", "strokeWidth": 0 },
        "borderWidth": 2,
        "shadow": { "enabled": true, "size": 5 }
      },
      "interaction": {
        "hover": true,
        "tooltipDelay": 200,
        "navigationButtons": true
      }
    }
    """)
    
    return net.generate_html()

# ------------------------------------------------------------------
# HIGH-LEVEL API FOR FASTAPI
# ------------------------------------------------------------------
def get_graph_data(
    selected_policies: Optional[List[str]] = None,
    module6_results: Optional[Dict[Tuple[str, str], Dict[str, Any]]] = None,
    stale_ids: Optional[Set[str]] = None,
) -> Dict[str, Any]:
    """Orchestrates the entire graph building process."""
    G = build_graph(module6_results, stale_ids)
    
    if selected_policies:
        G = filter_graph_by_policies(G, selected_policies)
    
    html = generate_pyvis_html(G)
    
    return {
        "graph_html": html,
        "node_count": G.number_of_nodes(),
        "edge_count": G.number_of_edges(),
        "nodes": list(G.nodes(data=True))[:100],
    }

if __name__ == "__main__":
    # Test harness execution when running direct
    print("Graph builder module verified and import-ready.")
